name: build and test CI workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        java-version: '14'
    - name: Build project with Maven
      run: mvn -B compile --file pom.xml

  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        java-version: '14'
    - name: Run tests
      run: mvn -B verify --file pom.xml
